server:
  session-timeout: 1800
  tomcat:
      max-threads: 10000
      min-spare-threads: 30
      max-connections: 30000


  port: 8081
#    uri-encoding: utf-8
#security:
#  basic:
#    enabled: false
encryption:
  server:
    private:
      key: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAKOlUzxMLl7pN0cPDcuQ0T5LuwP/IOWGdyvYpmgcUneVqY6nSz5X5xVqUjvHZKlh25/SO4feSiBDTu+naOlsVtsUARs95OAHS0j10mh8URJ6oR97SfY87lddTxm/ynEm8voOUW8cpiz0UZFqu9XAi0GSgcb21Vh+/wxSwrEC1r1nAgMBAAECgYArbsuiq017X0aOk45DwxHmCM+ABgzDHmcuufegljPFDXHNLNWpnEb2xhtBRnCPDCvwRSoLq5Hc8kBXFwWfPmPmoKl+Mkj+tjdbm2SM0AxwGu/U167C/JE253TShxJg+iYXRLnM6pO03myMOUQx8Dk0ByUbjq4H3NOZfnVTdZtCcQJBANaaG7pe1a9AJYXA1M3vt4oU5/7+rcBRB/Li1l3VMJgcy5dLbLSAD+MlVo5+tSE2pLPIsHq/4A3tvVXh1YQtQB0CQQDDNsy2IpA6V5W5enPLNWfmgtwJadPI/xo+1UJ4wdPna+2bTTgP5Gv7SAlw4a7oOaz3UHbFaeIht7PNpt7szIRTAkA1RsEHfa+y+EvYbszl61M3doU56uQb0IIWrHXniZusx8lLYDA2h2xqScS5T3+MJVKyR2p4rtXi31iXz58AV3OJAkEAtLeAX4QzvK7kPqarl41DOFQgWt6LXuE6bLyEIsJc5zo05rZflebCSAdyJfvnLbhm9TSaHztcShaD73fxm4nhXQJAEugmxDk5UI64he/Hrj/Y2I4WEwV5VTArXVfciofmVeduw21X09JNFfQW+2HlYVf7mLjOO8axwoKPqTP/IMlocA==
  client:
    public:
      key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCaq3H4qOas2LMpp5jhp0druoPAccSiFrwT6mgxgxnIBtalrMX39o3LmVvOGaOKoA0nevz4WU2vM4EEbM+ZJmJWt+PSl8IwC3P/yx6rLSOXos7xzjZAnhs1EXfWX6EEzkGue3/BKIcBK1v6LsPpOlT289o5cta4+Tc9LgBNhsMsqwIDAQAB





spring:
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 30Mb
      max-request-size: 30Mb
  devtools:
    restart:
      enabled: true
  cache:
    type: ehcache
    ehcache:
      config: classpath:config/ehcache.xml
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mybatis/**/*Mapper.xml
  typeAliasesPackage: com.waoqi.**.domain
#[弃用]配置缓存和session存储方式，默认ehcache,可选redis,[弃用]调整至 spring cache type【shiro.用户，权限，session，spring.cache通用】
#[弃用]cacheType: ehcache
