waoqi:
  uploadPath: /www/files/
  username: test123
  password: 111111123
  domain: http://admin.guozhijian.net
  password_encryption: fpC0baWr1OZCukcv
aliyun:
  accessKeyId: aaaaa
  accessSecret: bbbbbb
logging:
  level:
    root: error
    com.waoqi: info
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-2zers1c3a7xjrnay5.mysql.rds.aliyuncs.com:3306/lm_shop?useUnicode=true&characterEncoding=utf8
#    url: jdbc:mysql://rm-2zers1c3a7xjrnay5do.mysql.rds.aliyuncs.com:3306/lm_shop?useUnicode=true&characterEncoding=utf8
    username: lm_shop_online
    password: Guozhijian!@#456
    initialSize: 100
    minIdle: 200
    maxActive: 200
    # 配置获取连接等待超时的时间
    maxWait: 10000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 86400
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true
  redis:
      host: r-2zeed106921154a4pd.redis.rds.aliyuncs.com
      port: 6379
      password: gzj666__
      # 连接超时时间（毫秒）
      timeout: 10000
      jedis:
        pool:
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池中的最小空闲连接
          min-idle: 10
          # 连接池最大连接数（使用负值表示没有限制）
          max-active: 100
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1
